In [2]:
import numpy as np

 1. Create a random vector of size 30 and find the mean value

In [9]:
v =np.random.rand(1,30)
v.mean()

0.44459557886446266

2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

In [79]:
v = np.arange(1,11,0.4)
v=v.reshape(5,5)
numero_linha = v.shape[0]
numero_col = v.shape[1]

In [80]:
for i in range(numero_linha):
    for j in range(numero_col):
        if i>j:
            v[i][j] = np.random.randint(1,5)
v

array([[ 1. ,  1.4,  1.8,  2.2,  2.6],
       [ 4. ,  3.4,  3.8,  4.2,  4.6],
       [ 4. ,  4. ,  5.8,  6.2,  6.6],
       [ 2. ,  2. ,  2. ,  8.2,  8.6],
       [ 1. ,  1. ,  1. ,  4. , 10.6]])

3. How to find common values between two arrays?

4. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [58]:
v =np.random.randint(1,10,10)
mask = (v>3) & (v<8) #Não podemos esquecer dos parêntesis para criar a indexação booleana
v[mask]

array([6, 5, 5, 5, 5, 5, 7])

5. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

6. Create a 5x5 matrix with row values ranging from 0 to 4

In [13]:
np.arange(0,4,0.16).reshape((5,5))

array([[0.  , 0.16, 0.32, 0.48, 0.64],
       [0.8 , 0.96, 1.12, 1.28, 1.44],
       [1.6 , 1.76, 1.92, 2.08, 2.24],
       [2.4 , 2.56, 2.72, 2.88, 3.04],
       [3.2 , 3.36, 3.52, 3.68, 3.84]])

7. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [19]:
qtde_nume = (1-0.1)/10

np.arange(0.1,1,qtde_nume)

array([0.1 , 0.19, 0.28, 0.37, 0.46, 0.55, 0.64, 0.73, 0.82, 0.91])

8. Create random vector of size 10 and replace the maximum value by 0

In [44]:
v =np.random.rand(1,10)
v=10*v
posicao = np.argmax(v)
posicao
v[0][posicao] = 0
v

array([[2.56972522, 8.9628673 , 0.        , 4.52532574, 9.47428949,
        6.37851948, 1.51759851, 5.98588629, 2.49832545, 9.1787749 ]])

9. How to find the closest value (to a given scalar) in a vector?

10. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))